### ISSUE TITLE
Connection broken: ConnectionResetError(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by followingjpg** [ping/instagram_private_api_extensions#9]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- Please read the questions **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue make sure you have:
- [X] Updated to the lastest version v0.3.8
- [X] Read the [README](https://github.com/ping/instagram_private_api_extensions/blob/master/README.md)
- [X] [Searched](https://github.com/ping/instagram_private_api_extensions/search?type=Issues) the bugtracker for similar issues including **closed** ones

---

### Describe your Question/Issue:

Please make sure the description is worded well enough to be understood with as much context and examples as possible.

hi, im currently having the following problem "ChunkedEncodingError", is this the server side problem that im probably being banned? or the function     
def _download(self, target, output, timeout=None, init_chunk=None):
is not looping for retrying
looking forward for your response 
tks

Exception in thread 17935931611257555-25025.m4v:
Traceback (most recent call last):
  File "/home/goodpdt/.local/lib/python3.5/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/home/goodpdt/.local/lib/python3.5/site-packages/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/goodpdt/.local/lib/python3.5/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/goodpdt/.local/lib/python3.5/site-packages/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/goodpdt/.local/lib/python3.5/site-packages/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/goodpdt/.local/lib/python3.5/site-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/goodpdt/.local/lib/python3.5/site-packages/instagram_private_api_extensions/live.py", line 336, in _download
    }, timeout=timeout or self.download_timeout)
  File "/home/goodpdt/.local/lib/python3.5/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/goodpdt/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/goodpdt/.local/lib/python3.5/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/home/goodpdt/.local/lib/python3.5/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/goodpdt/.local/lib/python3.5/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

**Comment by ping** [comment]
[ConnectionResetError](https://docs.python.org/3/library/exceptions.html#ConnectionResetError)

You have a connection problem to IG servers. If you're using popular vps providers, it may be blocked.
